<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Citrus.Trading/Citrus.Trading.csproj" />
    <ProjectReference Include="../Citrus.Simulation/Citrus.Simulation.csproj" />
    <ProjectReference Include="../Citrus.Data/Citrus.Data.csproj" />
    <ProjectReference Include="../Citrus.Strategies/Citrus.Strategies.csproj" />
  </ItemGroup>
</Project>
