<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Citrus.Contracts/Citrus.Contracts.csproj" />
    <ProjectReference Include="../Citrus.Simulation/Citrus.Simulation.csproj" />
    <ProjectReference Include="../Citrus.Data/Citrus.Data.csproj" />
    <Reference Include="Microsoft.CodeAnalysis"><HintPath>$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.dll</HintPath><Private>true</Private></Reference>
    <Reference Include="Microsoft.CodeAnalysis.CSharp"><HintPath>$(MSBuildToolsPath)/Roslyn/bincore/Microsoft.CodeAnalysis.CSharp.dll</HintPath><Private>true</Private></Reference>
  </ItemGroup>
</Project>
