<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Citrus.Trading/Citrus.Trading.csproj" />
    <ProjectReference Include="../Citrus.Simulation/Citrus.Simulation.csproj" />
    <ProjectReference Include="../Citrus.Data/Citrus.Data.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
  </ItemGroup>
</Project>
