<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Citrus.Engine/Citrus.Engine.csproj" />
    <ProjectReference Include="../../src/Citrus.Strategies/Citrus.Strategies.csproj" />
    <None Include="Fixtures/Data/*.csv" Link="Data/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
