<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/Citrus.Engine/Citrus.Engine.csproj" /><None Include="../../examples/PaydaySeasonality/Strategy.cs" Link="PaydaySeasonality.cs" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>
